### ISSUE TITLE
Does go2sky plan to support go micro v2?

### ISSUE THREAD

**Issue by xtudouh** [SkyAPM/go2sky-plugins#11]
As the titile, our project use go micro v2 as web framework, and go micro v2 use opentracing as the tracing solution, does go2sky plan to support opentracing, As I know, skywalking implements opentracting, so does this client  plan to support.

**Comment by arugal** [comment]
>  does go2sky plan to support opentracing, As I know, skywalking implements opentracting, so does this client plan to support.

We have no plans at the moment. In the `go-micro` v2 version, there is a [SpanType](https://github.com/asim/go-micro/blob/b57f56fb0b92e711d7e9d61bd88aba94aa8ca3e0/debug/proto/debug.proto#L78) that conflicts with the [go2sky](https://github.com/SkyAPM/go2sky/blob/master/reporter/grpc/language-agent/Tracing.proto#L75), this is the key problem blocking us.

**Comment by wu-sheng** [comment]
@arugal Is the naming conflict? I think logically, those are not conflict.

**Comment by arugal** [comment]
> @arugal Is the naming conflict? I think logically, those are not conflict.

![image](https://user-images.githubusercontent.com/26432832/105503609-c405d880-5d01-11eb-8edb-f4182b7cf48b.png)

Yes, `proto: duplicate enum registerd` appears when used together.

**Comment by wu-sheng** [comment]
That is why we have updated the proto. :) Take a look, namespace added to avoid this kind of conflict.

**Comment by wu-sheng** [comment]
Old proto is still working as we provide the compatible mode at the OAP side :) But also, we updated the proto too.
