### ISSUE TITLE
Go调用PHP api无法形成链路?

### ISSUE THREAD

**Issue by srunze** [SkyAPM/go2sky-plugins#13]
用的这个示例代码：https://github.com/SkyAPM/go2sky-plugins/blob/master/gin/v3/example_gin_test.go
PHP有三个项目都装好扩展 01、02、03，可以访问01可以正常形成链路。
Go用的gin框架请求其他项目（Go\PHP），skwalking UI中访问日志确实有上报了但追踪不到完整的链路(看到PHP SERVER中是有HTTP_SW8这个值的）

VNode: 9f3948606e9b11eba790acde48001122（Go1 访问 Go2 两次追踪无关，但Go2的开始是这么个东西）
Broken - VirtualNode: #0
    /GET/gin/index
    Http - Gin

**Comment by wu-sheng** [comment]
`VirtualNode` means the data never reported. Read FAQ of SkyWalking.

**Comment by srunze** [comment]
> `VirtualNode` means the data never reported. Read FAQ of SkyWalking.

`
func (p *Index) Index(c *gin.Context) {
	//tracer, err := helpers.InitSkyWalking()
	r, err := reporter.NewGRPCReporter("http://172.16.143.2:11800")
	if err != nil {
		fmt.Println("new reporter error", err)
	}
	tracer, err := go2sky.NewTracer("default-go-example", go2sky.WithReporter(r))

	//NewClient returns an HTTP Client with tracer
	client, err := h.NewClient(tracer)
	if err != nil {
		fmt.Println("NewClient error", err)
	}
	url := "http://01.project.vm/php/demo"
	url = "http://localhost:4000/gin/demo"
	request, err := http.NewRequest("GET", url, nil)
	if err != nil {
		fmt.Println("NewRequest error", err)
	}

	resp, err := client.Do(request)
	if err != nil {
		fmt.Println("do error", err)
	}
	defer resp.Body.Close()

	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		// handle error
	}

	fmt.Println("result", string(body))
}

func (p *Index) Demo(c *gin.Context) {
	c.JSON(200, gin.H{"name": "demo", "path": c.Request.URL.Path})
}
`
访问地址`http://localhost:4000/gin/index` -> index内部访问`http://localhost:4000/gin/demo`
上述代码，主要的问题是这没有像PHP中一样有完整的链路呈现呢？

skywalking UI
**/gin/index表现**
/GET/gin/index
Http - Gin

**/gin/demo表现**
VNode: fb13f5246f8e11eb9ac8acde48001122
Broken - VirtualNode: #0
    /GET/gin/demo
    Http - Gin

**Comment by leeyisoft** [comment]
问题解决了吗？如何解决的呢？
