### ISSUE TITLE
go2sky如何整合echo框架

### ISSUE THREAD

**Issue by sunhongdou** [SkyAPM/go2sky-plugins#14]
echo框架中如何使用go2sky,当前没有适配该框架，后续是否有该计划？

**Comment by wu-sheng** [comment]
go2sky exposes all APIs you need, you could do this by your own, or better contribute up the upstream.

**Comment by sunhongdou** [comment]
e.Use(func(handlerFunc echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			// Use gRPC reporter for production
			//re, err := reporter.NewGRPCReporter("127.0.0.1:18810")
			re, err := reporter.NewLogReporter()
			if err != nil {
				log.Fatalf("new reporter error %v \n", err)
			}
			defer re.Close()

			tracer, err := go2sky.NewTracer("echo-server", go2sky.WithReporter(re))
			if err != nil {
				log.Fatalf("create tracer error %v \n", err)
			}
			
			
			if tracer == nil {
				return handlerFunc(c)
			}
			span, ctx, err := tracer.CreateEntrySpan(c.Request().Context(), getOperationName(c), func() (string, error) {
				return c.Request().Header.Get(propagation.Header), nil
			})

			if err != nil {
				return handlerFunc(c)
			}

			span.SetComponent(5004)
			span.Tag(go2sky.TagHTTPMethod, c.Request().Method)
			span.Tag(go2sky.TagURL, c.Request().Host+c.Request().URL.Path)
			span.SetSpanLayer(1)
			c.Request().WithContext(ctx)
			span.Tag(go2sky.TagStatusCode, strconv.Itoa(c.Response().Status))
			if c.Response().Status >= 400 {
				span.Error(time.Now(), string(c.Response().Body))
			}
			span.End()
			return handlerFunc(c)
		}
	})

**Comment by sunhongdou** [comment]
```
e.Use(func(handlerFunc echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			// Use gRPC reporter for production
			//re, err := reporter.NewGRPCReporter("127.0.0.1:18810")
			re, err := reporter.NewLogReporter()
			if err != nil {
				log.Fatalf("new reporter error %v \n", err)
			}
			defer re.Close()

			tracer, err := go2sky.NewTracer("echo-server", go2sky.WithReporter(re))
			if err != nil {
				log.Fatalf("create tracer error %v \n", err)
			}
			
			
			if tracer == nil {
				return handlerFunc(c)
			}
			span, ctx, err := tracer.CreateEntrySpan(c.Request().Context(), getOperationName(c), func() (string, error) {
				return c.Request().Header.Get(propagation.Header), nil
			})

			if err != nil {
				return handlerFunc(c)
			}

			span.SetComponent(5004)
			span.Tag(go2sky.TagHTTPMethod, c.Request().Method)
			span.Tag(go2sky.TagURL, c.Request().Host+c.Request().URL.Path)
			span.SetSpanLayer(1)
			c.Request().WithContext(ctx)
			span.Tag(go2sky.TagStatusCode, strconv.Itoa(c.Response().Status))
			if c.Response().Status >= 400 {
				span.Error(time.Now(), string(c.Response().Body))
			}
			span.End()
			return handlerFunc(c)
		}
	})
```

**Comment by wu-sheng** [comment]
Are you going to submit the pull request to us?
