### ISSUE TITLE
Feature - GORM v2 plugin implementation

### ISSUE THREAD

**Issue by kehuili** [SkyAPM/go2sky-plugins#36]
GORM is a commonly used ORM framework among Golang applications.

GORM plugin implementation is used for tracing DB operations, based on [GORM callback](https://gorm.io/docs/write_plugins.html#Callbacks).

PR would be ready to go if this feature Issue is accepted.

Preview
![image](https://user-images.githubusercontent.com/35578392/141672021-10470b61-7a2b-4998-aaa4-3543d4aad07f.png)

**Comment by wu-sheng** [comment]
First of all, from license perspective, it is OK to add. 
But I have a question for your screenshot, it shows component as MySQL(Database), I assume it was trying to present GORM?

**Comment by kehuili** [comment]
> First of all, from license perspective, it is OK to add. But I have a question for your screenshot, it shows component as MySQL(Database), I assume it was trying to present GORM?

Yes, because I used MySQL as database so it looked as shown above. Do I need to add a component named GORM?

**Comment by wu-sheng** [comment]
It depends, with GORM running, does user still need to use `go-sql-driver/mysql` plugin?(just an example).

**Comment by kehuili** [comment]
> It depends, with GORM running, does user still need to use `go-sql-driver/mysql` plugin?(just an example).

No need to use. User only need GORM package to operation databases.

**Comment by wu-sheng** [comment]
OK, then, not adding GORM as component seems making more sense. As the leaf exit span, it is better to have correct client side component name, which make the icon on the topology correctly representing the database server node.
