### ISSUE TITLE
Rollback error after mysql database transaction Commit

### ISSUE THREAD

**Issue by dingyalin** [SkyAPM/go2sky-plugins#38]
code：
```
tx := db.BeginTx(ctx, &sql.TxOptions{})
defer tx.Rollback()
...
 tx.Commit()
```

output：
```
panic: send on closed channel

goroutine 281 [running]:
github.com/SkyAPM/go2sky.(*rootSegmentSpan).End.func1(0xc0006167b0)
       vendor/github.com/SkyAPM/go2sky/segment.go:209 +0x4e
created by github.com/SkyAPM/go2sky.(*rootSegmentSpan).End
        vendor/github.com/SkyAPM/go2sky/segment.go:208 +0x85
exit status 2
```

**Comment by arugal** [comment]
Hi @kagaya85 Do you have time to take a look?

**Comment by kagaya85** [comment]
> Hi @kagaya85 Do you have time to take a look?

Ok, I will take a look.

**Comment by kagaya85** [comment]
Hi @dingyalin, the channel will be closed after root segment span is END, so if you use `Rollback` after `Commit`, it will call the `span.End()` once again and cause the `send on closed channel` panic. Actually, rollback after commit is not reasonable, even the `database/sql` will return the `ErrTxDone` error if use `Commit` and `Rollback` at the same time.

So, you can handle this in upper logic to avoid this, if you have some special scenario, we can also consider to add span closed check or some way to avoid panic and return an wrapped error. Welcome to continue to discuss.

**Comment by dingyalin** [comment]
@kagaya85 rollback after commit ErrTxDone  can ignore, but span.End() once again cause the send on closed channel panic .
How can I optimize panic to error?

**Comment by wu-sheng** [comment]
`span.End()` should only be called after `commit` successfully, then you would not face span ended panic.
