### ISSUE TITLE
go get go2sky-plugins/gin/v3 got an error not found

### ISSUE THREAD

**Issue by tingqiu814** [SkyAPM/go2sky-plugins#41]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN="/mypath/golang/bin"
GOCACHE="/mypath/Library/Caches/go-build"
GOENV="/mypath/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/mypath/golang/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/mypath/golang"
GOPRIVATE=""
GOPROXY="mycompay proxy"
GOROOT="/usr/local/go"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8z/tdm1jlhd5bz6d0k23qnszh293z9ph6/T/go-build2977867570=/tmp/go-build -gno-record-gcc-switches -fno-common"

</pre></details>

### What did you do?
go get -u github.com/SkyAPM/go2sky-plugins/gin/v3

### What did you expect to see?
expect import package without error

### What did you see instead?
$ go get -u github.com/SkyAPM/go2sky-plugins/gin/v3
go get: module github.com/SkyAPM/go2sky-plugins@upgrade found (v1.3.0), but does not contain package github.com/SkyAPM/go2sky-plugins/gin/v3

**Comment by arugal** [comment]
![image](https://user-images.githubusercontent.com/26432832/143515248-801dc760-3eb1-4d01-b78a-dd2da69ba6ca.png)

Please check your environment
